### ISSUE TITLE
Ad-hoc text and copy fixes

### ISSUE THREAD

**Issue by shanzzam** [stellar/account-viewer-next#157]
Coming out of the v1 testing before launch. 

- [x] Add ability to handle decimals in the send/receive boxes.
"it's a weird experience to try to enter 0.01 for example" Can keep the 'text' input type here? 

- [ ] Make the text input field size to be the same as the border, so the selected state outline will be around the entire field

- [x] Make spacing consistent in the Send modal. spacing between "Sending to" and Amount is bigger than the others. "Remove memo" could be closer to the memo fields. Check with Design.

- [ ] Implement new states for buttons. Dependent on Designs.

**Comment by quietbits** [comment]
New issue created for remaining items: https://github.com/stellar/account-viewer-next/issues/171
