### ISSUE TITLE
Cannot send a Memo with the Ledger Nano S?

### ISSUE THREAD

**Issue by etale-cohomology** [stellar/account-viewer-next#222]
Hopefully this is the repo for the Stellar Account Viewer that's currently live at `https://accountviewer.stellar.org`.

I tried sending a transaction to Binance (which requires a memo ID).
I wrote the memo ID in the box where you're supposed to write it.
When I checked the transaction details on the Ledger Nano S device, I saw the correct address but the Memo field was empty (on the device screen).
I tried sending it anyways to see what would happen. It didn't reach the Binance account, so I'm assuming the Memo wasn't sent.
I tried doing the same thing through another Stellar Wallet that supports the Nano S. The device screen did show the Memo ID, and the transaction reached the Binance account.

I'm using the latest Nano S firmware and the latest Stellar app version (for the Nano S).

**Comment by quietbits** [comment]
Hi @etale-cohomology,
This is the correct repo for new Account Viewer. Thanks for taking the risk of checking it and reporting this issue! Our dev team is out this week for the holidays, but we'll get to this as soon as we get back next week.

**Comment by shanzzam** [comment]
@etale-cohomology This issue has been addressed with https://github.com/stellar/account-viewer-next/pull/226
Please let us know if you run into any other issues!
