### ISSUE TITLE
Ensure scamming possibilities are as low as possible

### ISSUE THREAD

**Issue by acharb** [stellar/account-viewer-next#8]
Ideas to avoid scams

- Make secret key a secondary option
- Display a warning about safety and ask the user to always check the domain
- Detect user's paste action and display a warning
- Write an article about using password managers - the idea is that if the user is in a fake domain the pw manager won't try to fill the secret key
- Webhook to report if account viewer is running on a non-stellar.org domain

**Comment by leighmcculloch** [comment]
>Make secret key a secondary option

What would be the primary login option?

>Detect user's paste action and display a warning

Would this be paste of a secret key or something else?

**Comment by acharb** [comment]
Good questions. I copied these over from our brainstorming docs to consolidate. I believe they were written by @brunomuler if he wants to elaborate, but I imagine they will be addressed in the wireframes coming. I understood them as:

Primary login options would be signing in with another wallet eg. Ledger. You'd still be able to sign in with secret key but it wouldn't be the top of the page.

Pasting the secret key correct.

**Comment by leighmcculloch** [comment]
>Pasting the secret key correct.

Is our hope that a user would manually type out their secret key? Or to just highlight to them that when pasting their key they should make sure they trust the website? The secret keys are 56 characters long, so I don't think we can expect them to type them out manually.

**Comment by vcarl** [comment]
I believe the idea is to discourage entering it manually at all, in favor of a password manager, hardware wallet, or Lyra-esque tool. Still allow it as an escape hatch of sorts, but flagging it with "yo this is super dangerous and how most people get scammed" when we detect it.
